import type { Metadata } from "next";
import Script from 'next/script';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*
          Remove attributes injected by browser extensions early to avoid
          hydration mismatches (e.g. Grammarly adds data-gr-ext-installed).
          This script runs before React hydrates via next/script's beforeInteractive
          strategy so server HTML and client DOM match at hydration time.
        */}
        <Script id="clean-extension-attrs" strategy="beforeInteractive">
          {`(function(){
            try{
              var attrs = ['data-new-gr-c-s-check-loaded','data-gr-ext-installed','data-gr-ext'];
              attrs.forEach(function(a){ if(document && document.body && document.body.hasAttribute(a)) document.body.removeAttribute(a); });
            }catch(e){/* ignored */}
          })()`}
        </Script>
        {children}
      </body>
    </html>
  );
}
